### ISSUE TITLE
关于训练的讨论

### ISSUE THREAD

**Issue by juneboat** [CDOTAD/AlphaGAN-Matting#4]
你好，最近我也在这个模型去做课题，训练也碰上一些GD的平衡问题，可以留个联系方式讨论下吗？：）

**Comment by CDOTAD** [comment]
> 你好，最近我也在这个模型去做课题，训练也碰上一些GD的平衡问题，可以留个联系方式讨论下吗？：）

好的，我的邮箱是 zlzhang18@fudan.edu.cn 你可以在邮件里告诉我你的微信什么的，哈哈

**Comment by juneboat** [comment]
> > 你好，最近我也在这个模型去做课题，训练也碰上一些GD的平衡问题，可以留个联系方式讨论下吗？：）
> 
> 好的，我的邮箱是 [zlzhang18@fudan.edu.cn](mailto:zlzhang18@fudan.edu.cn) 你可以在邮件里告诉我你的微信什么的，哈哈

已发到你邮箱了：）
