### ISSUE TITLE
Could you offer pretrained model?

### ISSUE THREAD

**Issue by wodsoe** [CDOTAD/AlphaGAN-Matting#6]
Could you offer pretrained model?

**Comment by CDOTAD** [comment]
The result is bad. As it was just a course project, I have no longer worked on it. I strongly recommend you to train it yourself. If you still want the model file, you could send me an email.

**Comment by tearhupo121031** [comment]
> The result is bad. As it was just a course project, I have no longer worked on it. I strongly recommend you to train it yourself. If you still want the model file, you could send me an email.

could you please give me your email address?
